repos:
-   repo: local
    hooks:
    -   id: wily
        name: wily
        entry: wily diff
        verbose: true
        language: python
        additional_dependencies: [wily]
    -   id: coverage
        name: coverage
        language: system
        entry: coverage run -m pytest
        types: [python]
        pass_filenames: false